### ISSUE TITLE
points_to_route fails with error

### ISSUE THREAD

**Issue by riccardoklinger** [anitagraser/QGIS-Processing-tools#12]
current error is: 
Uncaught error while executing algorithm
Traceback (most recent call last):
Traceback (most recent call last):
  File "C:/PROGRA~1/QGISBR~1/apps/qgis/./python/plugins\processing\core\GeoAlgorithm.py", line 212, in execute
    self.processAlgorithm(progress)
  File "C:/PROGRA~1/QGISBR~1/apps/qgis/./python/plugins\processing\script\ScriptAlgorithm.py", line 264, in processAlgorithm
    exec(script) in ns
  File "<string>", line 51, in <module>
IndexError: list index out of range

Sample lines and points can be found here: http://www.digital-geography.com/wp-content/uploads/2015/01/wd_hapag.zip

I am using the script just with lines and points. so no fancy stuff involved. Both datasets are in EPSG 4326.

**Comment by riccardoklinger** [comment]
used wrong version from this repo as there was one for qgis 2.6.
